### ISSUE TITLE
[SE Panel] - Word-Breaking in Cards

### ISSUE THREAD

**Issue by Ratismal** [StreamElements/api-docs#23]
Salutations,

This isn't related to the docs, but this repository was the most relevant place I could find to post this issue in.

This issue is regarding the CSS of cards on the web panel, specifically in the `.item-description` class. The property `word-break` is set to `break-all`, which allows breaks to be placed in between any characters. This leads to undesirable and ugly rendering.

For example,
![with break-all](https://requires.discord.gold/e320b4.png)

Now with the `word-break` rule disabled:
![without break-all](https://requires.discord.gold/afc8fa.png)

Having line breaks in the middle of words decreases readability. Please resolve this issue.

**Comment by Ian321** [comment]
Closing all issues related to the old website.
If you have any questions you can check out our [discord](https://discord.gg/se).
