### ISSUE TITLE
Removing more points than a user has

### ISSUE THREAD

**Issue by stackola** [StreamElements/api-docs#24]
When removing points from a user's account, it would be nice to get information about the actual amount of points removed.

For example, if I remove 50 points from a user that only has 10, the response still says 

`Removed -50 points to user USERNAME`

I think either it should throw an error in this case, and not remove any coins at all, or it should at least return the actual number of points removed, in this case 10.

**Comment by CSMarco** [comment]
@stackola Nice suggestion!
If you want you get the points that where removed from the user you can just make an API request before to get the current points of the user (https://github.com/StreamElements/api-docs/blob/master/points.md#get-pointschannelusername) and get the difference of the points yourself by comparing the newAmount parameter of the response and the amount of current points that you got from the response before.

Maybe it will be added by default in StreamElements API v2, which should be released soon, but for now you could handle it like described above ;)

**Comment by stackola** [comment]
Your described solution isn't transaction safe, as the user could conceivably spend their points between the first and second request.

**Comment by CSMarco** [comment]
@stackola Yeah I know, but I can't think of another solution with the current API ^^

**Comment by Ian321** [comment]
Closing all issues related to the old API.
If you have any questions you can check out our [discord](https://discord.gg/se).
