### ISSUE TITLE
GET/DELETE on /bot/timers/:id have different formats

### ISSUE THREAD

**Issue by dangercrow** [StreamElements/api-docs#28]
--> GET /bot/timers/:[ID]
<-- 200 OK
--> GET /bot/timers/[ID]
<-- 404 Not Found

--> DELETE /bot/timers/:[ID]
<-- 404 (with HTML body with message `Cannot DELETE /kappa/v1/bot/timers/`)
--> DELETE /bot/timers/[ID]
<-- 200 `{ "statusCode": 201, "message": "Timer was deleted"}`

Looks like the colon must be **present** for GET, and **absent** for DELETE

**Comment by Ian321** [comment]
Closing all issues related to the old API.
If you have any questions you can check out our [discord](https://discord.gg/se).
