### ISSUE TITLE
POST tip?

### ISSUE THREAD

**Issue by Ceneka** [StreamElements/api-docs#34]
I have an app which allow to post tips into another system because in our country we are unable to use Paypal. Is there a way to do such thing on Streamelements?

**Comment by CSMarco** [comment]
@Ceneka As far as I know it is not possible yet, but be patient StreamElements API v2 is coming soon :)

**Comment by Ian321** [comment]
Closing all issues related to the old API.
If you have any questions you can check out our [discord](https://discord.gg/se).
